export const FACEBOOK_PAGE_LIST = "FACEBOOK_PAGE_LIST";
export const FACEBOOK_PAGE_CONNECTED = "FACEBOOK_PAGE_CONNECTED";
export const FACEBOOK_GROUP_LIST = "FACEBOOK_GROUP_LIST";
export const FACEBOOK_GROUP_CONNECTED = "FACEBOOK_GROUP_CONNECTED";
export const FACEBOOK_PROFILE_LIST = "FACEBOOK_PROFILE_LIST";
export const FACEBOOK_PROFILE_CONNECTED = "FACEBOOK_PROFILE_CONNECTED";
