export const DO_INVITE_MEMBER = "DO_INVITE_MEMBER";
export const DO_INVITE_MEMBER_List = "DO_INVITE_MEMBER_List";
export const PASSIVE_INVITE_MEMBER_LIST = "PASSIVE_INVITE_MEMBER_LIST";
export const DO_INVITE_MEMBER_LIST_WITHOUT_SEARCH =
  "DO_INVITE_MEMBER_LIST_WITHOUT_SEARCH";
export const EMPTY_TEAMS_MEMBERS = "EMPTY_TEAMS_MEMBERS";
