export const MEMBER_DELETE = "MEMBER_DELETE";
export const TYPE_ADD_MEMBER = 'TYPE_ADD_MEMBER';
export const GET_MEMBER_LIST = 'GET_MEMBER_LIST';
export const GET_MEMBER_DETAILS = "GET_MEMBER_DETAILS";
export const UPDATE_MEMBER_DETAILS = "UPDATE_MEMBER_DETAILS";
